version: '3'

services:
  db:
    container_name: db
    image: mariadb
    environment:
      - MYSQL_DATABASE=airquality_it
      - MYSQL_USER=airquality_it
      - MYSQL_PASSWORD=airquality_it
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  web:
    container_name: web
    build: .
    command: ./wait-for-it.sh db:3306 -- gunicorn -b 0.0.0.0:8000 airquality_itkmitl.wsgi
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY=ABCDEFG123456789
      - DJANGO_DEBUG=True
      - DATABASE_USER=airquality_it
      - DATABASE_PASS=airquality_it
      - DATABASE_NAME=airquality_it
      - DATABASE_HOST=db
