version: '3'

services:
  web:
    container_name: web
    restart: always
    build: .
    command: gunicorn -b 0.0.0.0:8000 airquality_itkmitl.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
