version: '3'

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: airquality_it
      MYSQL_ROOT_PASSWORD: 12345678
  web:
    container_name: web
    build: .
    command: gunicorn -b 0.0.0.0:8000 airquality_itkmitl.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: .env.development
