# Generated by Django 2.1.5 on 2019-02-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.FloatField(null=True, verbose_name='PM2.5 (µm/m^3)')),
                ('pm10', models.FloatField(null=True, verbose_name='PM10 (µm/m^3)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Air Quality',
                'verbose_name_plural': 'Air Quality',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=1000, null=True)),
                ('longitude', models.CharField(max_length=25, null=True)),
                ('latitude', models.CharField(max_length=25, null=True)),
                ('token', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='airquality',
            name='device_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='external_api.Device'),
        ),
    ]
