# Generated by Django 2.1.5 on 2019-02-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0002_auto_20190201_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='pm10',
            field=models.FloatField(default=0, verbose_name='PM10 (µm/m^3)'),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='pm25',
            field=models.FloatField(default=0, verbose_name='PM2.5 (µm/m^3)'),
        ),
    ]
