# Generated by Django 2.1.5 on 2019-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0003_auto_20190201_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='airquality',
            name='pm1',
            field=models.FloatField(default=0, verbose_name='PM1 (µm/m^3)'),
        ),
    ]
