# Generated by Django 2.1.5 on 2019-02-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0004_airquality_pm1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airquality',
            old_name='pm25',
            new_name='pm250',
        ),
        migrations.RemoveField(
            model_name='airquality',
            name='pm1',
        ),
        migrations.AddField(
            model_name='airquality',
            name='pm100',
            field=models.FloatField(default=0, verbose_name='PM10 (µm/m^3)'),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='pm10',
            field=models.FloatField(default=0, verbose_name='PM1 (µm/m^3)'),
        ),
    ]
