version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Start the django container && Run the django unittest
          command: |
            docker-compose -f docker-compose.test.yml up -d
            docker exec web ./wait-for-it.sh db:3306 -- python manage.py test
      - run:
          name: Build and Push Docker image
          command: |
            docker build . -t chin8628/airquality_itkmitl_web
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push chin8628/airquality_itkmitl_web
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o StrictHostKeyChecking=no root@cloudian.in.th "bash /home/boonyarith/circleci-script/airquality_it deploy.sh"

