version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    dependencies:
      override:
        - sudo pip install --upgrade docker-compose==1.3.0
    steps:
      - checkout
      - run:
          name: Django test
          command: |
            docker-compose run web python manage.py test
      - run:
          name: Run Tests
          command: |
            python manage.py test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t chin8628/airquality-itkmitl .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push chin8628/$airquality-itkmitl
      # - run:
      #     name: Deploy app to Digital Ocean Server via Docker
      #     command: |
      #       ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"
